name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25.7

    - name: Install dependencies
      run: go mod download

    - name: Lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        golangci-lint run

    - name: Unit Tests
      run: go test ./...

    - name: Build
      run: go build ./cmd/server

    - name: Docker Build
      run: docker build -t iso-gateway .